### PR TITLE
Fix HTTP error messages

### PR DESCRIPTION
**Pull request by zerebubuth**
Thanks to @mmd-osm for pointing this out in #124.

It looks like this sort of worked as of #83, although returning HTML rather than plain text as the Rails code does. That was sort of fixed in 1d0e06f2bdcbb5efc5ec7908e79d5d4e65fd139f to match the behaviour of _most_ of the Rails errors: which is to print a blank string as the error. Unfortunately, the side effect was disabling display in the body of all messages.

This branch tries to fix this, first by printing the error messages in the response body and secondly by providing error messages for all the various `not_found` cases.

This is a departure from strict compatibility with the Rails code. However, most of the `not_found` messages that the Rails code generates are translations from `ActiveRecord::RecordNotFound`. If I remember correctly, at the time of writing it was difficult to tell exactly _what_ hadn't been found, although I see that [more information might be available now](http://api.rubyonrails.org/classes/ActiveRecord/RecordNotFound.html). I think the best thing is to provide a meaningful error message in cgimap, and I'll try to come up with a similar patch for the Rails code.

@tomhughes what do you think?

### CODE REVIEW

**Comment by tomhughes** [comment]
Does the rails code return anything in the body? I thought it was just the `Error` header unless you asked for XML errors, because it was odd to return a different sort of document on error...

**Comment by tomhughes** [comment]
Looks like rails does also return a text body with the error so I guess this is fine.

Whether the person who contacted ops this week would have noticed the body any more than the error header is an open question ;-)

**Comment by zerebubuth** [comment]
My reading of [`application_controller.rb:287`](https://github.com/openstreetmap/openstreetmap-website/blob/96c91757fc23023f2d56019252a9f89f2482266f/app/controllers/application_controller.rb#L287) is that it does, when a message is available. But it looks like [not found explicitly returns the empty string](https://github.com/openstreetmap/openstreetmap-website/blob/96c91757fc23023f2d56019252a9f89f2482266f/app/controllers/application_controller.rb#L318).

I suppose we could replace the body with `<script>alert("#{error_message}");</script>`, but I figure that would get annoying very quickly :wink:

**Comment by zerebubuth** [comment]
Upon further investigation, it looks like the extra details in `ActiveRecord::RecordNotFound` are only in [Rails 5.0.1 or later](https://github.com/rails/rails/commit/d763956ed95bce581f12151a5ed4df12bcefdeee). And Rails 5 is still burning hot from the oven...

In the meantime, I'll just leave this how it is for the moment. One small fix: looks like Rails doesn't support the XML error stuff for 404s, so I'll make it match that.

**Comment by tomhughes** [comment]
Is that sort of bug-for-bug compatibility really sensible? Shouldn't we just fix the rails code? Why does it special case record not found?

**Comment by tomhughes** [comment]
Looking at it I guess the logic is that a 404 has meaning on it's own. Quite why it is giving text/html for a `:text => ""` render is another question...

**Pull request merged**
