### PR TITLE
Add default_transaction_read_only 

### LINKED ISSUE #90: Use default_transaction_read_only
Good practices dictate using a user who only has the minimum access required, but running `set default_transaction_read_only = true;` at the start of transaction would be a good idea as an additional security layer.

### PR DESCRIPTION
**Pull request by jronak**
Fixes #90 

Thanks!

### CODE REVIEW

**Comment by zerebubuth** [comment]
I'm not 100% sure, but I think #90 was intended for the writeable backend. We use the readonly one for replica databases, which are read-only already. Having this would help make the tests fail in case we did something non-read-only, so I think we should have it for both backends. @pnorman, what do you think?

**Comment by pnorman** [comment]
I think we should have it on both, and the writable apidb is more important. In production we only run the readonly queries on replicas, but there's no reason it can't be run against a normal database.

**Comment by jronak** [comment]
We have writeable queries in the write apidb, so should the read_only be set only for select queries?

**Comment by pnorman** [comment]
I was thinking that read-only could be used with temporary tables, but was wrong. Trying to do it for only some queries with the writable apidb backend is probably not worth it because it would inhibit connection pooling.

I guess the appropriate way to do this is to run cgimap on a postgres user which only has SELECT access, and then only access to the tables and columns it needs

**Comment by zerebubuth** [comment]
The [PostgreSQL docs](https://www.postgresql.org/docs/current/static/sql-set-transaction.html) say:

> When a transaction is read-only, the following SQL commands are disallowed: `INSERT`, `UPDATE`, `DELETE`, and `COPY FROM` if the table they would write to is not a temporary table; all `CREATE`, `ALTER`, and `DROP` commands; `COMMENT`, `GRANT`, `REVOKE`, `TRUNCATE`; and `EXPLAIN ANALYZE` and `EXECUTE` if the command they would execute is among those listed.

Does that mean that we should set the default transaction to read-only, then start an explicitly writeable transaction to create the temporary tables? All the other creations of `pqxx::work`, which start transactions, should then be read-only, but still able to insert into the temporary table.

**Comment by pnorman** [comment]
Doing setup then going to read-only might be an option. It's just the CREATE statements which are a problem.

**Comment by jronak** [comment]
Updated PR, please review.

**Comment by zerebubuth** [comment]
Wonderful. Thank you!

**Pull request merged**
