### PR TITLE
Ubuntu 20.04 (Focal) adjustments

### PR DESCRIPTION
**Pull request by mmd-osm**
Thanks to previous work in #200, unit tests passed without changes.

In this pull request, remaining deprecation and compiler warnings will be fixed.

### CODE REVIEW

**Comment by tomhughes** [comment]
What's the status of this?

**Comment by mmd-osm** [comment]
I fixed all remaining compiler warnings now, that were all due to some deprecation in libpqxx.

**Comment by mmd-osm** [comment]
Re: Chef error on Ubuntu 20.04 (_Error executing action `upgrade` on resource 'apt_package[openstreetmap-cgimap-bin])_':

I will set up a new branch `ubuntu/focal` once this pull request is merged, then build a new PPA for Focal. 

By the way, up-porting the existing 18.04 PPA to Focal should also work, as this Pull request is about fixing compiler warnings only.

**Comment by mmd-osm** [comment]
The first **test** build for Ubuntu 20.04 just finished. Build process on launchpad now also includes all database related tests.

https://launchpad.net/~mmd-osm/+archive/ubuntu/cgimap-focal-test-6/+packages

**Comment by tomhughes** [comment]
Any idea when we might have a new release with 20.04 support now this is merged?

**Comment by mmd-osm** [comment]
July timeframe should be feasible. The new configuration file option is still pretty much undocumented, which isn’t good enough for a release yet. A bit of additional testing on errol (running on 20.04) also wouldn’t hurt. Do you need a new ppa build for focal and bionic, or would focal only do as well?

**Comment by tomhughes** [comment]
Well errol isn't upgraded yet. It's probably best not to upgrade at the same time as doing the OS so I guess packages for both is probably a good idea so we can do the upgrade to cgimap first and then the OS.

**Comment by tomhughes** [comment]
I have now upgraded errol to Ubuntu 20.04...

**Comment by mmd-osm** [comment]
Since you've copied over the new packages to ~osmadmins earlier today: I forgot to post an update here last week about the new 0.8.3 packages for Bionic and Focal over at https://launchpad.net/~mmd-osm/+archive/ubuntu/cgimap

**Comment by tomhughes** [comment]
Yes I just noticed you had copied them to your main repo so I copied them over and deployed them...

**Pull request merged**
