### PR TITLE
MacOS issues reported in #455

### LINKED ISSUE #455: Compilation errors when building on macOS
Continued https://github.com/zerebubuth/openstreetmap-cgimap/pull/454

To build on macOS, you can use the following workflow as a basis:

https://github.com/deevroman/openstreetmap-cgimap/blob/4d8c571bd797418cb16757e69a142b60f1132796/.github/workflows/macos_14.yml

Problems that I found when compiling on my Apple M1
1.

 ```
/Users/runner/work/openstreetmap-cgimap/openstreetmap-cgimap/src/fcgi_request.cpp:161:56: error: invalid operands to binary expression ('int' and 'std::nullptr_t')
        if (strerror_r(errno, err_buf, sizeof err_buf) == nullptr) {
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~
[ 11%] Linking CXX static library ../../libcgimap_libxml++.a
[ 11%] Built target cgimap_libxml++
1 error generated.
```

The function declaration looks like this: `int	 strerror_r(int __errnum, char *__strerrbuf, size_t __buflen);` It is necessary to compare with 0 instead of nullptr.

2. 
```
In file included from /Users/deevroman/Documents/GitHub/openstreetmap-cgimap/contrib/sjparser/library/sjparser/yajl_parser.cpp:24:
/Users/deevroman/Documents/GitHub/openstreetmap-cgimap/contrib/sjparser/library/sjparser/yajl_parser.h:26:10: fatal error: 'yajl/yajl_parse.h' file not found
#include <yajl/yajl_parse.h>
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
```

The problem is in the external dependency of sjparser, but there is an assumption that you need to deal with FindYAJL. cmake. I'll try to debug it. As a workaround, I moved the files from `/opt/homebrew/Cellar/yajl/2.1.0/include/yajl` to the library directory and replaced <yajl/yajl_parse.h> to "yajl_parse. h"

3. 
```
/Users/deevroman/Documents/GitHub/openstreetmap-cgimap/src/main.cpp:86:17: error: use of undeclared identifier 'HOST_NAME_MAX'
  char hostname[HOST_NAME_MAX];
                ^
```

On macOS you will have to set this constant manually https://github.com/eddic/fastcgipp/issues/13#issuecomment-271894079

4.
```
/Users/deevroman/Documents/GitHub/openstreetmap-cgimap/src/../include/cgimap/api06/changeset_upload/node.hpp:35:20: error: call to deleted function 'from_chars'
    auto [_, ec] = std::from_chars(lat.data(), lat.data() + lat.size(), _lat);
                   ^~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/c++/v1/__charconv/from_chars_integral.h:37:19: note: candidate function has been explicitly deleted
from_chars_result from_chars(const char*, const char*, bool, int = 10) = delete;
                  ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/c++/v1/__charconv/from_chars_integral.h:223:1: note: candidate template ignored: requirement 'is_integral<double>::value' was not satisfied [with _Tp = double]
from_chars(const char* __first, const char* __last, _Tp& __value) {
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/c++/v1/__charconv/from_chars_integral.h:229:1: note: candidate function template not viable: requires 4 arguments, but 3 were provided
from_chars(const char* __first, const char* __last, _Tp& __value, int __base) {
^
1 error generated.
``` 

Similar error in the `set_lon` function. This is an Apple Clang issue: https://stackoverflow.com/questions/74955092/using-the-correct-to-chars-overload

5.
```
/Users/deevroman/Documents/GitHub/openstreetmap-cgimap/src/backend/apidb/pgsql_update.cpp:179:12: error: no matching function for call to 'max'
    return std::max(bbox_size_limit, 0L);
           ^~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/c++/v1/__algorithm/max.h:40:1: note: candidate template ignored: deduced conflicting types for parameter '_Tp' ('long long' vs. 'long')
max(_LIBCPP_LIFETIMEBOUND const _Tp& __a, _LIBCPP_LIFETIMEBOUND const _Tp& __b)
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/c++/v1/__algorithm/max.h:51:1: note: candidate template ignored: could not match 'initializer_list<_Tp>' against 'long long'
max(initializer_list<_Tp> __t, _Compare __comp)
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/c++/v1/__algorithm/max.h:60:1: note: candidate function template not viable: requires single argument '__t', but 2 arguments were provided
max(initializer_list<_Tp> __t)
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/c++/v1/__algorithm/max.h:31:1: note: candidate function template not viable: requires 3 arguments, but 2 were provided
max(_LIBCPP_LIFETIMEBOUND const _Tp& __a, _LIBCPP_LIFETIMEBOUND const _Tp& __b, _Compare __comp)
^
1 error generated.
```

Probable fix: 0L -> 0LL

6. 
```
In file included from /Users/deevroman/Documents/GitHub/openstreetmap-cgimap/src/request.cpp:15:
In file included from /opt/homebrew/include/fmt/core.h:5:
In file included from /opt/homebrew/include/fmt/format.h:41:
/opt/homebrew/include/fmt/base.h:1643:3: error: static assertion failed due to requirement 'formattable': Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt
  static_assert(
  ^
/opt/homebrew/include/fmt/base.h:2018:20: note: in instantiation of function template specialization 'fmt::detail::make_arg<true, fmt::context, request::workflow_status, 0>' requested here
  return {{detail::make_arg<NUM_ARGS <= detail::max_packed_args, Context>(
                   ^
/opt/homebrew/include/fmt/format.h:4365:28: note: in instantiation of function template specialization 'fmt::make_format_args<fmt::context, request::workflow_status, request::workflow_status, 2UL, 0UL, 255ULL, 0>' requested here
  return vformat(fmt, fmt::make_format_args(args...));
                           ^
/Users/deevroman/Documents/GitHub/openstreetmap-cgimap/src/request.cpp:95:35: note: in instantiation of function template specialization 'fmt::format<request::workflow_status &, request::workflow_status &>' requested here
    throw std::runtime_error(fmt::format("Can't move backwards in the request workflow from {} to {}.",
                                  ^
1 error generated.
```

I haven’t come up with a fix yet, so I commented out this code

7. 
```
In file included from /Users/deevroman/Documents/GitHub/openstreetmap-cgimap/src/handler.cpp:10:
In file included from /Users/deevroman/Documents/GitHub/openstreetmap-cgimap/src/../include/cgimap/handler.hpp:16:
In file included from /Users/deevroman/Documents/GitHub/openstreetmap-cgimap/src/../include/cgimap/data_update.hpp:15:
/Users/deevroman/Documents/GitHub/openstreetmap-cgimap/src/../include/cgimap/util.hpp:79:33: error: no member named 'join' in namespace 'fmt'
  return fmt::format("{}", fmt::join(ids, ","));
                           ~~~~~^
1 error generated.
```

Error due to missing header `#include <fmt/ranges.h>`

### PR DESCRIPTION
**Pull request by mmd-osm**
Fixes #455

### CODE REVIEW

**Comment by deevroman** [comment]
I cloned the repository from this branch: everything compiled without errors!

**Comment by mmd-osm** [comment]
Ok, great. I think what’s left now is to add unit tests for macOS…

**Comment by deevroman** [comment]
I don't know if you've already figured out what the problem is with the test "Tag: Value with max 255 unicode characters, <= 255"

The behavior of mbsrtowcs is somehow different for Linux and macOS for the same 64-character string 😎

Linux vs macOS 

<table>

<tr>

<td>



<td>




</table>

**Comment by mmd-osm** [comment]
No idea really why mbsrtowcs isn't working as expected. I've added another one-liner implementation for macOS now. Some deprecation warnings have been silenced, which is ok for now.

pg_virtualenv tests on a real database instance are currently disabled, since that tool seems to be unavailable on macOS. Maybe this could be addressed in another PR.

**Comment by mmd-osm** [comment]
By the way, thanks for the GH action file. I've cherry picked your commit, so that you're officially listed as contributor for this repo now.

**Comment by mmd-osm** [comment]
By the way, I had to disable macOS again in GH actions. It is 10 times more expensive than the other runners, and consumes too much of the available free quota. Hopefully this will stop random freezes that are happening for quite some time now.

**Comment by deevroman** [comment]
> It is 10 times more expensive

Wow. Maybe disable running tests on macOS in pull requests and leave it only for push in master?

**Comment by mmd-osm** [comment]
I've pretty much disabled macOS everywhere now. Having a working pipeline has higher prio at the moment. Maybe I'll do some more experiments next month when the quota gets reset. Here's how a typical day looks like:

image

**Pull request merged**
