### PR TITLE
Sync test db schema with upstream openstreetmap-website

### PR DESCRIPTION
**Pull request by Woazboat**
\+ Add required non-null redaction description field in test data
\+ Set UTF8 server encoding for temporary test databases (required for unicode normalization)

Requires https://github.com/zerebubuth/openstreetmap-cgimap/pull/405

### CODE REVIEW

**Comment by mmd-osm** [comment]
I'm wondering why we need the explicit `--encoding=UTF8` for `pg_virtualenv`, while this place https://github.com/zerebubuth/openstreetmap-cgimap/actions/runs/8943146217/job/24567227952#step:3:1283 seems to figure out utf8 as a default. 

Could we use a single CREATE DATABASE ... ENCODING 'UTF8' here instead: https://github.com/zerebubuth/openstreetmap-cgimap/blob/master/test/test_database.cpp#L77

**Comment by Woazboat** [comment]
Unfortunately the build job link doesn't show the log for me, but I assume you mean this?
```
2024-05-03T18:14:14.8541038Z #6 34.95 /usr/lib/postgresql/16/bin/initdb -D /var/lib/postgresql/16/main --auth-local peer --auth-host scram-sha-256 --no-instructions
2024-05-03T18:14:14.8543268Z #6 34.96 The files belonging to this database system will be owned by user "postgres".
2024-05-03T18:14:14.8544232Z #6 34.96 This user must also own the server process.
2024-05-03T18:14:14.8544736Z #6 34.96 
2024-05-03T18:14:14.8545839Z #6 34.97 The database cluster will be initialized with locale "C.UTF-8".
2024-05-03T18:14:14.8547480Z #6 34.97 The default database encoding has accordingly been set to "UTF8".
2024-05-03T18:14:14.8549021Z #6 34.97 The default text search configuration will be set to "english".
```

Good question. `pg_createcluster`/`initdb` use the system locale, so either apt does something special during installation or the locale is somehow different.

**Comment by mmd-osm** [comment]
Yes, exactly, here's the log snippet i was referring to:
```
#6 34.77 Setting up g++-13 (13.2.0-23ubuntu4) ...
#6 34.77 Setting up postgresql-16 (16.2-1ubuntu4) ...
#6 34.94 Creating new PostgreSQL cluster 16/main ...
#6 34.95 /usr/lib/postgresql/16/bin/initdb -D /var/lib/postgresql/16/main --auth-local peer --auth-host scram-sha-256 --no-instructions
#6 34.96 The files belonging to this database system will be owned by user "postgres".
#6 34.96 This user must also own the server process.
#6 34.96 
#6 34.97 The database cluster will be initialized with locale "C.UTF-8".
#6 34.97 The default database encoding has accordingly been set to "UTF8".
#6 34.97 The default text search configuration will be set to "english".
#6 34.97 
#6 34.97 Data page checksums are disabled.
#6 34.97 
#6 34.97 fixing permissions on existing directory /var/lib/postgresql/16/main ... ok
#6 34.97 creating subdirectories ... ok
#6 34.97 selecting dynamic shared memory implementation ... posix
```

**Comment by Woazboat** [comment]
Looks like debian uses C.UTF8 as the default encoding for the initial cluster created during installation if no other locale is configured
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=790507

    Use C.UTF-8 instead of C when the initial main cluster is created and no
    locale is configured explicitly as system default. (Closes: #[790507](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=790507))

**Comment by mmd-osm** [comment]
I tried this one https://github.com/mmd-osm/openstreetmap-cgimap/commit/0b8528286dc437f3556bd093889bc9addb048ff7 to avoid adding the encoding parameter in multiple places across CMakeLists.txt. It seems to achieve the same goal.

**Comment by Woazboat** [comment]
Changed to your version, although I wonder if there are other assumptions about the database locale elsewhere in the code.

**Comment by Woazboat** [comment]
> Run docker run --entrypoint /bin/bash cgimap:trixie -c "/usr/local/bin/openstreetmap-cgimap --help"
  docker run --entrypoint /bin/bash cgimap:trixie -c "/usr/local/bin/openstreetmap-cgimap --help"
  shell: /usr/bin/bash -e {0}
##[debug]/usr/bin/bash -e /home/runner/work/_temp/9e8dfc36-2280-4239-8ade-485e841cc8b0.sh
/usr/local/bin/openstreetmap-cgimap: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /usr/local/bin/openstreetmap-cgimap)

Debian testing packaging seems to be a bit broken at the moment unfortunately. (Don't ask me how I know or or how long I spent fixing my system on Monday evening...)

**Comment by mmd-osm** [comment]
I've disabled Trixie for now...

**Pull request merged**
