### PR TITLE
More cleanup

### PR DESCRIPTION
**Pull request by Woazboat**

### CODE REVIEW

**Comment by mmd-osm** [comment]
Regarding the formatting topic, maybe we could check, if there's a easy way to automate the process in the future. You've probably seen the section  in `Makefile.am` below, which unfortunately no longer works as is: directory names are incomplete / outdated, the style file "`file`" doesn't really exist, the existing style file "`.clang-format`" may no longer be up-to-date, etc.

It would be really good to get this up and running again. clang-format as part of Github Actions would also be cool. Maybe this could be achieved with little additional effort, once the style file is in a good shape again.

```Makefile
if HAVE_CLANG_FORMAT
.PHONY: clang-format
clang-format:
	@echo "Reformatting files..."; \
	for i in include/api06/*.hpp; do @CLANG_FORMAT@ -style=file -i $$i; done; \
	for i in include/cgimap/api06/*.hpp; do @CLANG_FORMAT@ -style=file -i $$i; done; \
	for i in include/cgimap/api07/*.hpp; do @CLANG_FORMAT@ -style=file -i $$i; done; \
	for i in include/cgimap/backend/apidb/*.hpp; do @CLANG_FORMAT@ -style=file -i $$i; done; \
	for i in include/cgimap/backend/staticxml/*.hpp; do @CLANG_FORMAT@ -style=file -i $$i; done; \
	for i in include/cgimap/*.hpp; do @CLANG_FORMAT@ -style=file -i $$i; done; \
	for i in include/*.hpp; do @CLANG_FORMAT@ -style=file -i $$i; done; \
	for i in src/api06/*.cpp; do @CLANG_FORMAT@ -style=file -i $$i; done; \
	for i in src/api07/*.cpp; do @CLANG_FORMAT@ -style=file -i $$i; done; \
	for i in src/backend/apidb/*.cpp; do @CLANG_FORMAT@ -style=file -i $$i; done; \
	for i in src/backend/staticxml/*.cpp; do @CLANG_FORMAT@ -style=file -i $$i; done; \
	for i in src/*.cpp; do @CLANG_FORMAT@ -style=file -i $$i; done; \
	for i in test/*.cpp; do @CLANG_FORMAT@ -style=file -i $$i; done;
endif

```

**Comment by Woazboat** [comment]
The codebase could definitely use a clang format pass. That should probably be a separate commit/PR though.

**Comment by mmd-osm** [comment]
> I could remove the formatting commit here and leave that for a clang format pass later?

Yes, I believe that's a good idea. Some files like readonly_pgsql_selection.cpp would need a bit of work before running clang-format, to keep it from breaking all the SQL statement formatting. Here we could either add some comments like

```
// clang-format off
...
// clang-format on
```

... or convert the SQL statements to raw string literals.

**Comment by mmd-osm** [comment]
Thanks! I cherry-picked all commits except for 0e49384775788dea0a312aaaf233d26ffa439e70, and moved them to #333. Some of my local changes started to cause conflicts with e963ff2ec92f794cc6d0376cf8cef6f9e28b3ac4, which I also resolved at the same time.

My proposal would be to rerun the formatting at a later point in time.

**Comment by Woazboat** [comment]
I removed the format only commit, but https://github.com/zerebubuth/openstreetmap-cgimap/commit/0e49384775788dea0a312aaaf233d26ffa439e70 had some include header cleanup which is why I left it in.

**Comment by mmd-osm** [comment]
Ah, you're right, I mixed this up. Will try to get https://github.com/zerebubuth/openstreetmap-cgimap/commit/0e49384775788dea0a312aaaf233d26ffa439e70 in now as well...

**Pull request closed without merging**
